### ISSUE TITLE
Create smart contract for Pentamidine isethionate

### ISSUE THREAD

**Issue by LauraVilladakommit** [kommitters/okdose-dapp#18]
ℹ️ This issue is part of Epic #14 

## Objective

Create a smart contract to calculate the dosage for Pentamidine isethionate for Leishmaniasis, a disease transmitted by vectors. There are a preparation and treatment time field in the contract response with the following information:

Preparation
- Reconstitute each ampoule with 5 mL of water for injections.
- Take blood glucose and blood pressure before administration.
- Apply the calculated volume IM.
- Concomitantly, administer IV 100 to 200 mL of 5% DAD for 30 min.
- Observe the patient for 1 hour controlling vital signs and glucometry.
- Cite in 48 hours for the next dose.

Treatment time: Cutaneous Leishmaniasis = 4 doses Mucocutaneous Leishmaniasis = 7 to 15 dosis Visceral Leishmaniasis = 7 to 15 doses

## Checklist

- [ ] The smart contract calculates the correct dosage for Pentamidine isethionate
- [ ] The smart contract has been deployed to the testnet
- [ ] There is a preparation field in the response with the text specified
- [ ] There is a unit test for the smart contract

**Comment by keliumJU** [comment]
Hello, I can take this issue?
